version: "3.8"


services:
  mongodb:
    image: mongo:latest
    container_name: sneakers-mongo
    restart: always

    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    
    ports:
      - "27017:27017"

      

    