// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/sneaker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sneaker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Model          string  `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer   string  `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Colorway       string  `protobuf:"bytes,4,opt,name=colorway,proto3" json:"colorway,omitempty"`
	Price          float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Deprecated     bool    `protobuf:"varint,6,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	AvailableSizes []int32 `protobuf:"varint,7,rep,packed,name=available_sizes,json=availableSizes,proto3" json:"available_sizes,omitempty"`
}

func (x *Sneaker) Reset() {
	*x = Sneaker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sneaker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sneaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sneaker) ProtoMessage() {}

func (x *Sneaker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sneaker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sneaker.ProtoReflect.Descriptor instead.
func (*Sneaker) Descriptor() ([]byte, []int) {
	return file_proto_sneaker_proto_rawDescGZIP(), []int{0}
}

func (x *Sneaker) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sneaker) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Sneaker) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Sneaker) GetColorway() string {
	if x != nil {
		return x.Colorway
	}
	return ""
}

func (x *Sneaker) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Sneaker) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Sneaker) GetAvailableSizes() []int32 {
	if x != nil {
		return x.AvailableSizes
	}
	return nil
}

type SneakerGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SneakerGetAllReq) Reset() {
	*x = SneakerGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sneaker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SneakerGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SneakerGetAllReq) ProtoMessage() {}

func (x *SneakerGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sneaker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SneakerGetAllReq.ProtoReflect.Descriptor instead.
func (*SneakerGetAllReq) Descriptor() ([]byte, []int) {
	return file_proto_sneaker_proto_rawDescGZIP(), []int{1}
}

type SneakerGetByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SneakerGetByIdReq) Reset() {
	*x = SneakerGetByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sneaker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SneakerGetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SneakerGetByIdReq) ProtoMessage() {}

func (x *SneakerGetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sneaker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SneakerGetByIdReq.ProtoReflect.Descriptor instead.
func (*SneakerGetByIdReq) Descriptor() ([]byte, []int) {
	return file_proto_sneaker_proto_rawDescGZIP(), []int{2}
}

func (x *SneakerGetByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSneakerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSneakerMsg) Reset() {
	*x = DeleteSneakerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sneaker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSneakerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSneakerMsg) ProtoMessage() {}

func (x *DeleteSneakerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sneaker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSneakerMsg.ProtoReflect.Descriptor instead.
func (*DeleteSneakerMsg) Descriptor() ([]byte, []int) {
	return file_proto_sneaker_proto_rawDescGZIP(), []int{3}
}

type UpdateSneakerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSneakerMsg) Reset() {
	*x = UpdateSneakerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sneaker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSneakerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSneakerMsg) ProtoMessage() {}

func (x *UpdateSneakerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sneaker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSneakerMsg.ProtoReflect.Descriptor instead.
func (*UpdateSneakerMsg) Descriptor() ([]byte, []int) {
	return file_proto_sneaker_proto_rawDescGZIP(), []int{4}
}

type SneakerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model          string  `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer   string  `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Colorway       string  `protobuf:"bytes,3,opt,name=colorway,proto3" json:"colorway,omitempty"`
	Price          float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Deprecated     bool    `protobuf:"varint,5,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	AvailableSizes []int32 `protobuf:"varint,6,rep,packed,name=available_sizes,json=availableSizes,proto3" json:"available_sizes,omitempty"`
}

func (x *SneakerReq) Reset() {
	*x = SneakerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sneaker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SneakerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SneakerReq) ProtoMessage() {}

func (x *SneakerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sneaker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SneakerReq.ProtoReflect.Descriptor instead.
func (*SneakerReq) Descriptor() ([]byte, []int) {
	return file_proto_sneaker_proto_rawDescGZIP(), []int{5}
}

func (x *SneakerReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SneakerReq) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *SneakerReq) GetColorway() string {
	if x != nil {
		return x.Colorway
	}
	return ""
}

func (x *SneakerReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SneakerReq) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *SneakerReq) GetAvailableSizes() []int32 {
	if x != nil {
		return x.AvailableSizes
	}
	return nil
}

var File_proto_sneaker_proto protoreflect.FileDescriptor

var file_proto_sneaker_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x22,
	0xce, 0x01, 0x0a, 0x07, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x77, 0x61,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x77, 0x61,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x72, 0x65,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x65, 0x70,
	0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x73,
	0x22, 0x12, 0x0a, 0x10, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x22, 0x23, 0x0a, 0x11, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x12, 0x0a,
	0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0xc1, 0x01, 0x0a, 0x0a, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61,
	0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x77, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x77, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x73, 0x32, 0xc7, 0x02, 0x0a, 0x0e, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x12, 0x1a, 0x2e, 0x73, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6e,
	0x65, 0x61, 0x6b, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x73, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b,
	0x2e, 0x73, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x73, 0x6e,
	0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x45,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x2e, 0x73,
	0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x73, 0x6e, 0x65, 0x61,
	0x6b, 0x65, 0x72, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6e, 0x65, 0x61, 0x6b,
	0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x35, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x53, 0x6e, 0x65, 0x61,
	0x6b, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x73, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53,
	0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x73, 0x6e, 0x65, 0x61,
	0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0d,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x14, 0x2e,
	0x73, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x73, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x73,
	0x72, 0x61, 0x65, 0x6c, 0x2d, 0x46, 0x65, 0x72, 0x72, 0x65, 0x69, 0x72, 0x61, 0x2f, 0x73, 0x6e,
	0x65, 0x61, 0x6b, 0x65, 0x72, 0x73, 0x2d, 0x63, 0x72, 0x75, 0x64, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sneaker_proto_rawDescOnce sync.Once
	file_proto_sneaker_proto_rawDescData = file_proto_sneaker_proto_rawDesc
)

func file_proto_sneaker_proto_rawDescGZIP() []byte {
	file_proto_sneaker_proto_rawDescOnce.Do(func() {
		file_proto_sneaker_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sneaker_proto_rawDescData)
	})
	return file_proto_sneaker_proto_rawDescData
}

var file_proto_sneaker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_sneaker_proto_goTypes = []interface{}{
	(*Sneaker)(nil),           // 0: sneakers.Sneaker
	(*SneakerGetAllReq)(nil),  // 1: sneakers.SneakerGetAllReq
	(*SneakerGetByIdReq)(nil), // 2: sneakers.SneakerGetByIdReq
	(*DeleteSneakerMsg)(nil),  // 3: sneakers.DeleteSneakerMsg
	(*UpdateSneakerMsg)(nil),  // 4: sneakers.UpdateSneakerMsg
	(*SneakerReq)(nil),        // 5: sneakers.SneakerReq
}
var file_proto_sneaker_proto_depIdxs = []int32{
	1, // 0: sneakers.SneakerService.GetAll:input_type -> sneakers.SneakerGetAllReq
	2, // 1: sneakers.SneakerService.GetById:input_type -> sneakers.SneakerGetByIdReq
	2, // 2: sneakers.SneakerService.DeleteById:input_type -> sneakers.SneakerGetByIdReq
	5, // 3: sneakers.SneakerService.AddSneaker:input_type -> sneakers.SneakerReq
	5, // 4: sneakers.SneakerService.UpdateSneaker:input_type -> sneakers.SneakerReq
	0, // 5: sneakers.SneakerService.GetAll:output_type -> sneakers.Sneaker
	0, // 6: sneakers.SneakerService.GetById:output_type -> sneakers.Sneaker
	3, // 7: sneakers.SneakerService.DeleteById:output_type -> sneakers.DeleteSneakerMsg
	0, // 8: sneakers.SneakerService.AddSneaker:output_type -> sneakers.Sneaker
	4, // 9: sneakers.SneakerService.UpdateSneaker:output_type -> sneakers.UpdateSneakerMsg
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sneaker_proto_init() }
func file_proto_sneaker_proto_init() {
	if File_proto_sneaker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sneaker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sneaker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sneaker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SneakerGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sneaker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SneakerGetByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sneaker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSneakerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sneaker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSneakerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sneaker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SneakerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sneaker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sneaker_proto_goTypes,
		DependencyIndexes: file_proto_sneaker_proto_depIdxs,
		MessageInfos:      file_proto_sneaker_proto_msgTypes,
	}.Build()
	File_proto_sneaker_proto = out.File
	file_proto_sneaker_proto_rawDesc = nil
	file_proto_sneaker_proto_goTypes = nil
	file_proto_sneaker_proto_depIdxs = nil
}
